import os
from appJar import gui

inpu = "Str"
app = gui("Fichero", "500x680", useTtk=True)
app.setTtkTheme("arc")
app.startFrame("frame1",row=0,column=0)
app.addEntry("e1",colspan=2); app.setEntryDefault("e1", "Nombre")
app.addEntry("e3",colspan=2); app.setEntryDefault("e3", "Alias")
app.addEntry("e7",colspan=2); app.setEntryDefault("e7", "Peso")
app.addEntry("e9",colspan=2); app.setEntryDefault("e9", "Raza")
app.addEntry("e11",colspan=2); app.setEntryDefault("e11", "Sexualidad")
app.addEntry("e13",colspan=2); app.setEntryDefault("e13", "Gustos")
app.addEntry("e15",colspan=2); app.setEntryDefault("e15", "Estado Mental")
app.addEntry("e17",colspan=2); app.setEntryDefault("e17", "Enfermedad")
app.addEntry("e19",colspan=2); app.setEntryDefault("e19", "Debilidades")
app.stopFrame()


app.startFrame("frame2",row=0,column=1)
app.addEntry("e2",colspan=2); app.setEntryDefault("e2", "Apellido")
app.addEntry("e4",colspan=2); app.setEntryDefault("e4", "Edad")
app.addEntry("e6",colspan=2); app.setEntryDefault("e6", "Altura")
app.addEntry("e8",colspan=2); app.setEntryDefault("e8", "Tipo de Sangre")
app.addEntry("e10",colspan=2); app.setEntryDefault("e10", "Genero")
app.addEntry("e12",colspan=2); app.setEntryDefault("e12", "Preferencias")
app.addEntry("e14",colspan=2); app.setEntryDefault("e14", "Disgustos")
app.addEntry("e16",colspan=2); app.setEntryDefault("e16", "Especializaciones")
app.addEntry("e18",colspan=2); app.setEntryDefault("e18", "Habilidades Secundarias")
app.stopFrame()
app.startFrame("frame3",colspan=2)
app.addTextArea("e21",colspan=2); app.setTextArea("e21", "Apariencia")
app.stopFrame()
app.startFrame("frame4",row=1,column=1,colspan=2)
app.addTextArea("e5",colspan=2); app.setTextArea("e5", "Personalidad")
app.stopFrame()
app.addEntry("e20",colspan=2); app.setEntryDefault("e20", "Datos extra")
def press(button):
    if button == "Listo":
        inpu = str(app.getEntry("e1"))
        file = open(str(inpu) + ".txt", "w+")
        file.write("† `Nombre: " + str(inpu) + "`\n") 
        inpu = str(app.getEntry("e2"))
        file.write("† `Apellido: " + str(inpu) + "`\n")
        inpu = str(app.getEntry("e3"))
        file.write("† `Alias: " + str(inpu) + "`\n")
        file.write("`----------------------------------------------`\n")
        inpu = str(app.getEntry("e4"))        
        file.write("† `Edad: " + str(inpu) + "`\n")
        inpu = str(app.getTextArea("e5"))
        file.write("† `Personalidad: " + str(inpu) + "`\n") 
        inpu = str(app.getEntry("e6"))
        file.write("† `Altura: " + str(inpu) + "`\n") 
        inpu = str(app.getEntry("e7"))
        file.write("† `Peso: " + str(inpu) + "`\n") 
        inpu = str(app.getEntry("e8"))
        file.write("† `Tipo de Sangre: " + str(inpu) + "`\n") 
        inpu = str(app.getEntry("e9"))
        file.write("† `Raza: " + str(inpu) + "`\n")
        file.write("`----------------------------------------------`\n") 
        inpu = str(app.getEntry("e10"))
        file.write("† `Género: " + str(inpu) + "`\n")
        inpu = str(app.getEntry("e11"))
        file.write("† `Sexualidad: " + str(inpu) + "`\n") 
        inpu = str(app.getEntry("e12"))
        file.write("† `Preferencias: " + str(inpu) + "`\n")
        file.write("`----------------------------------------------`\n")  
        inpu = str(app.getEntry("e13"))
        file.write("† `Gustos: " + str(inpu) + "`\n") 
        inpu = str(app.getEntry("e14"))
        file.write("† `Disgustos: " + str(inpu) + "`\n")
        file.write("`----------------------------------------------`\n")  
        inpu = str(app.getEntry("e15"))
        file.write("† `Estado mental: " + str(inpu) + "`\n")
        file.write("`----------------------------------------------`\n")  
        inpu = str(app.getEntry("e16"))
        file.write("† `Especializaciones: " + str(inpu) + "`\n")
        inpu = str(app.getEntry("e17"))
        file.write("† `Enfermedad: " + str(inpu) + "`\n")
        file.write("`----------------------------------------------`\n")  
        inpu = str(app.getEntry("e18"))
        file.write("† `Habilidades Secundarias: " + str(inpu) + "`\n")
        file.write("`----------------------------------------------`\n") 
        inpu = str(app.getEntry("e19"))
        file.write("† `Debilidades: " + str(inpu) + "`\n")
        file.write("`----------------------------------------------`\n")
        inpu = str(app.getEntry("e20"))
        file.write("† `Datos extra: " + str(inpu) + "`\n")
        file.write("`----------------------------------------------`\n")
        inpu = str(app.getTextArea("e21"))
        file.write("† `Apariencia: " + str(inpu) + "`\n")
        file.write("`----------------------------------------------`\n")
    else:
        app.stop()  
        
app.addButtons(["Listo", "Salir"], press,colspan=4)
app.go()

